In [46]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=DataConversionWarning)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor
from sklearn.linear_model import SGDRegressor, LinearRegression, SGDClassifier
from xgboost import XGBClassifier, XGBRegressor
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 30)

In [4]:
df = pd.read_csv('ver1.csv', index_col=['id'])
# display(df.columns)
df.drop(columns=['production_countries', 'production_companies', 'genres', 'release_date', 
                 'popularity_norm', 'year', 'original_language', 'fr', 'ru', 'es', 'hi', 
                 'ja', 'it', 'ko', 'cn', 'zh', 'others', 'month', 'date'], inplace=True)

df_norm = df

df_norm_mean = df_norm.mean()
df_norm_std = df_norm.std()

df_norm = (df_norm - df_norm_mean) / df_norm_std
df_norm['en'] = df['en']
display(df_norm)


X = df_norm.drop(columns=['revenue'])
y = df_norm[['revenue']]
# X_train, X_test = train_test_split(df_norm, test_size = 0.1, random_state=123)

# X_train = pd.DataFrame(data=X_train)
# y_train = X_train[['revenue']]
# X_train = X_train.drop(columns=['revenue'])
# X_test = pd.DataFrame(data=X_test)
# y_test = X_test[['revenue']]
# X_test = X_test.drop(columns=['revenue'])

budget  popularity   revenue   runtime  vote_average  vote_count  \
id                                                                           
5      -0.837473   -0.182568 -0.635929 -0.615447      0.213421   -0.326808   
11     -0.680285    2.666589  3.479701  0.481086      2.058488    3.959233   
12      1.183519    1.546249  4.360033 -0.520096      1.481905    3.606166   
13      0.307756    2.989704  2.959561  1.482269      2.173805    4.875661   
14     -0.590463    1.413857  1.242805  0.528762      1.827855    1.630536   
...          ...         ...       ...       ...           ...         ...   
365222 -0.118898   -0.284649  0.178258 -0.281719      0.213421   -0.433010   
375290 -0.826245   -0.741973 -0.488084  0.719463      1.135955   -0.659479   
376659 -0.478185    0.357884  0.322854 -0.520096     -0.017212    0.180990   
381902  0.610680   -0.682117  0.374845  0.433411     -0.363162   -0.682689   
417859  1.991916   -0.243050  2.303290 -0.996850      0.098105   -0.382371   

         quarter  en  
id                    
5       1.253251   1  
11     -0.581184   1  
12     -0.581184   1  
13      0.336033   1  
14      0.336033   1  
...          ...  ..  
365222  1.253251   0  
375290 -1.498402   0  
376659  0.336033   1  
381902 -1.498402   0  
417859  1.253251   1  

[3169 rows x 8 columns]

In [29]:
ada_reg_dt = AdaBoostRegressor()

In [30]:
ada_reg_dt_dict = cross_validate(ada_reg_dt ,X, y, cv=20, return_train_score=True, return_estimator=True)

In [31]:
display(ada_reg_dt_dict['train_score'])
display(ada_reg_dt_dict['test_score'])

array([0.44526927, 0.69865067, 0.55897479, 0.53739965, 0.25624025,
       0.366671  , 0.38400747, 0.60377779, 0.56001956, 0.33031746,
       0.45776987, 0.17765165, 0.47805542, 0.61243419, 0.50257109,
       0.66436897, 0.47683237, 0.45063291, 0.47976738, 0.68548199])

array([ 4.59575470e-01,  6.13271151e-01,  4.73672645e-01,  5.52514008e-01,
       -1.45992919e+00, -1.22601778e+00,  1.23897555e-03,  2.73739522e-01,
        3.25831421e-01, -7.54841794e-01, -5.84623835e-01, -1.13163583e+00,
        4.76416025e-01,  5.51373762e-01,  5.07660225e-01,  6.23061068e-01,
        2.32271224e-01,  6.07554127e-01,  2.88965103e-01,  5.21886865e-01])

In [16]:
ada_reg_sgd = AdaBoostRegressor(base_estimator=SGDRegressor(learning_rate='adaptive', max_iter=3000))

In [17]:
ada_reg_sgd_dict = cross_validate(ada_reg_sgd ,X, y, cv=20, return_train_score=True, return_estimator=True)

In [18]:
display(ada_reg_sgd_dict['train_score'])
display(ada_reg_sgd_dict['test_score'])

array([0.34872986, 0.5425073 , 0.34289234, 0.32364621, 0.44279474,
       0.45042397, 0.51007352, 0.52473904, 0.26455931, 0.32167582,
       0.35733646, 0.52743218, 0.62410104, 0.40569561, 0.50449239,
       0.46164746, 0.55539606, 0.45815352, 0.65586416, 0.45120073])

array([ 0.5179934 ,  0.57904626,  0.2653434 ,  0.06391785, -0.25789532,
       -0.05919673,  0.39118673,  0.25791547, -0.19938277, -0.61081164,
       -0.12132047,  0.24191078,  0.69803788,  0.21831132,  0.53544791,
        0.20571149, -0.09199546,  0.73165706,  0.43167   ,  0.47432695])

In [20]:
ada_reg_lr = AdaBoostRegressor(base_estimator=LinearRegression())

In [21]:
ada_reg_lr_dict = cross_validate(ada_reg_lr ,X, y, cv=20, return_train_score=True, return_estimator=True)

In [22]:
display(ada_reg_lr_dict['train_score'])
display(ada_reg_lr_dict['test_score'])

array([0.63091806, 0.62492756, 0.63251013, 0.61831217, 0.60681655,
       0.64985541, 0.64321885, 0.61578857, 0.65817638, 0.65310678,
       0.6375406 , 0.65193507, 0.5660576 , 0.60749559, 0.66666762,
       0.63090224, 0.6314504 , 0.6210313 , 0.65346108, 0.62210879])

array([0.61769616, 0.58109462, 0.56872176, 0.53348791, 0.27038681,
       0.4750745 , 0.53417781, 0.45304637, 0.65059984, 0.4600668 ,
       0.5161773 , 0.61391083, 0.62438544, 0.52190794, 0.7151693 ,
       0.62973622, 0.03767393, 0.77406668, 0.35807645, 0.64292366])

In [34]:
y_bin = pd.qcut(y['revenue'], 10, labels=[*range(10)])

In [41]:
ada_clf_dt = AdaBoostClassifier()

In [59]:
ada_clf_dt_dict = cross_validate(ada_clf_dt ,X, y_bin, cv=20, return_train_score=True, return_estimator=True)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  ................................................................
[CV] ................ , score=(train=0.286, test=0.244), total=   0.2s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s


[CV] ................ , score=(train=0.289, test=0.256), total=   0.2s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.6s remaining:    0.0s


[CV] ................ , score=(train=0.289, test=0.244), total=   0.2s
[CV]  ................................................................
[CV] ................ , score=(train=0.283, test=0.269), total=   0.3s
[CV]  ................................................................
[CV] ................ , score=(train=0.277, test=0.269), total=   0.2s
[CV]  ................................................................
[CV] ................ , score=(train=0.270, test=0.225), total=   0.2s
[CV]  ................................................................
[CV] ................ , score=(train=0.280, test=0.300), total=   0.3s
[CV]  ................................................................
[CV] ................ , score=(train=0.288, test=0.325), total=   0.3s
[CV]  ................................................................
[CV] ................ , score=(train=0.281, test=0.206), total=   0.2s
[CV]  ................................................................
[CV] .

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    6.2s finished


In [44]:
display(ada_clf_dt_dict['train_score'])
display(ada_clf_dt_dict['test_score'])

array([0.28580924, 0.28946494, 0.28880027, 0.28348288, 0.27650382,
       0.26952476, 0.28015952, 0.28846793, 0.28148887, 0.28414756,
       0.28015952, 0.29411765, 0.27949485, 0.29345297, 0.29378531,
       0.29378531, 0.28737542, 0.28618748, 0.28817489, 0.28817489])

array([0.24375   , 0.25625   , 0.24375   , 0.26875   , 0.26875   ,
       0.225     , 0.3       , 0.325     , 0.20625   , 0.33125   ,
       0.25      , 0.25      , 0.30625   , 0.30625   , 0.3       ,
       0.2875    , 0.27044025, 0.22      , 0.25333333, 0.19333333])

In [56]:
xgb_reg = XGBClassifier(verbosity=1, n_jobs=4)

In [60]:
xgb_reg_dict = cross_validate(xgb_reg ,X, y, cv=20, return_train_score=True, return_estimator=True, verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  ................................................................


KeyboardInterrupt: 